name: Test Translations

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      # This isn't a package.json project, so we don't need to install dependencies
      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      - name: Run translation tests
        run: node test.js
